# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf68e0af1988e54916c5e31b4f43adae4858b132334ca7e8fe6e1e3f07820e777a52e1ffe6dda7d9ec1a7e369519d7f2d3fce736b8badaf9c0cd06094151a53a

test:
  secret_key_base: e4d2739e171f96a1adeac944b8e5896ed62c8dc7393bdeb76ce7d0eadb5ae69d57b648887300979d67a5e3268a8bbdb6660e671678045ad7e2365bea3e057fbb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
